"""Metadata store interface.

The backend core depends on this protocol only, so SQLite can be swapped for
PostgreSQL without touching resolution, planning or execution.
"""

from __future__ import annotations

from contextlib import AbstractContextManager
from typing import Any, Protocol

from ...core.models.entities import (
    Artifact,
    AuditEvent,
    Column,
    Dataset,
    DatasetVersion,
    LineageEdge,
    Operation,
    OutputContract,
)


class MetadataStore(Protocol):
    def transaction(self) -> AbstractContextManager[None]: ...
    def allocate_id(self, prefix: str) -> str: ...

    # datasets
    def insert_dataset(self, dataset: Dataset) -> None: ...
    def update_dataset(self, dataset: Dataset) -> None: ...
    def get_dataset(self, dataset_id: str, include_deleted: bool = False) -> Dataset | None: ...
    def get_dataset_by_name(self, name: str) -> Dataset | None: ...
    def list_datasets(self, include_deleted: bool = False) -> list[Dataset]: ...

    # columns
    def insert_columns(self, columns: list[Column]) -> None: ...
    def update_column(self, column: Column) -> None: ...
    def get_columns(self, dataset_id: str) -> list[Column]: ...

    # artifacts
    def insert_artifact(self, artifact: Artifact) -> None: ...
    def get_artifact(self, artifact_id: str) -> Artifact | None: ...
    def find_artifact(self, path: str, content_hash: str) -> Artifact | None: ...
    def list_artifacts(self) -> list[Artifact]: ...

    # versions
    def insert_version(self, version: DatasetVersion) -> None: ...
    def list_versions(self, dataset_id: str) -> list[DatasetVersion]: ...
    def get_version(self, dataset_id: str, version: int) -> DatasetVersion | None: ...
    def list_all_versions(self) -> list[DatasetVersion]: ...

    # lineage
    def insert_lineage_edge(self, edge: LineageEdge) -> None: ...
    def lineage_into(self, dataset_id: str) -> list[LineageEdge]: ...
    def lineage_out_of(self, dataset_id: str) -> list[LineageEdge]: ...

    # operations
    def insert_operation(self, operation: Operation) -> None: ...
    def update_operation(self, operation: Operation) -> None: ...
    def get_operation(self, operation_id: str) -> Operation | None: ...
    def list_operations(self, limit: int = 50) -> list[Operation]: ...

    # audit
    def insert_audit_event(self, event: AuditEvent) -> None: ...
    def list_audit_events(self, entity_id: str | None = None, operation_id: str | None = None) -> list[AuditEvent]: ...

    # output contracts
    def insert_contract(self, contract: OutputContract) -> None: ...
    def update_contract(self, contract: OutputContract) -> None: ...
    def get_contract(self, contract_id: str) -> OutputContract | None: ...
    def latest_contract(self) -> OutputContract | None: ...
    def list_contracts(self, limit: int = 50) -> list[OutputContract]: ...

    # idempotency
    def get_idempotent_response(self, key: str) -> dict[str, Any] | None: ...
    def save_idempotent_response(self, key: str, operation_id: str, response: dict[str, Any], created_at: str) -> None: ...

    def close(self) -> None: ...
